# Generated by Django 4.2 on 2026-09-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirebridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminphone',
            name='admin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hirebridge.adminprofile'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hirebridge.resume'),
        ),
        migrations.AlterField(
            model_name='cvscore',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hirebridge.resume'),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='hirebridge.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='hirebridge.resume'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='hirebridge.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resumes', to='hirebridge.adminprofile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='hirebridge.userprofile'),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirebridge.scoringcriteria'),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='cv_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hirebridge.cvscore'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hirebridge.resume'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='cv_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='hirebridge.cvscore'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hirebridge.userprofile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='hirebridge.resume'),
        ),
    ]
